name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Setup Buildozer and dependencies
      run: |
        # Установка системных инструментов
        sudo apt-get update && sudo apt-get install -y \
          python3-pip \
          openjdk-11-jdk \
          unzip zip wget git

        # Установка Buildozer
        pip install --upgrade buildozer cython

        # Установка Android SDK
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        rm commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools latest

        # Экспорт путей для Android SDK
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools

        # Принятие лицензий и установка компонентов
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;36.0.0" "platforms;android-33" "sources;android-33" "extras;android;m2repository"

        # Установка aidl
        sdkmanager "build-tools;30.0.3"

    - name: Build APK
      run: |
        cd ${{ github.workspace }}
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: APK
        path: bin/*.apk
