name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libffi-dev libssl-dev zlib1g-dev
        pip install --upgrade pip
        pip install buildozer cython

    - name: Accept Android SDK licenses
      run: |
        yes | ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses

    - name: Prepare Android SDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        buildozer android update

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: bin/*.apk   - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: bin/*.apk # Загружаем APK как артефакт
