name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Buildozer and system dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          python3-pip \
          openjdk-11-jdk \
          unzip zip wget git

        pip install --upgrade buildozer cython

    - name: Setup Android SDK
      run: |
        # Create directory for SDK tools
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools

        # Download command line tools for Android SDK
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        rm commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools latest

        # Export paths for SDK tools
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools

        # Accept licenses using awk to avoid Broken pipe issue
        sdkmanager --licenses | awk '/Accept?/ {print "y"}' | sdkmanager --licenses

        # Install necessary Android SDK components
        sdkmanager --install "platform-tools" "build-tools;36.0.0" "platforms;android-33" "sources;android-33" "extras;android;m2repository"

    - name: Verify Android SDK installation
      run: |
        # Ensure all required components are installed
        sdkmanager --list | grep "Installed" || echo "SDK components verified"

    - name: Build APK using Buildozer
      run: |
        cd ${{ github.workspace }}
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: bin/*.apk
